<?php
// $Id: invdb.module,v 1.2 2012/08/22 14:28:14 stephen Exp stephen $

/**
 * @file
 * will handle inventory data base interaction
 *
 */

/**
 * function to update the database based on data from the input.module
 * @method invdb_update_database($db_table, $data_array)
 * @param string             $db_table  name of the table to update
 * @param associative array  $data_array  array containg the data to update
 * @return integer           $inv_id  the row that was updated
 *
 */
function invdb_update_database($db_table, $data_array) {
  
  $table = $db_table;

  try {
  $inv_id = db_insert($table)
  ->fields(array(
		 'user_id' => $data_array['name'],
		 'asset_tag' => $data_array['fixed_asset_tag'],
		 'serial_num' => $data_array['serial-number'],
		 'cub_id' => $data_array['cubid'],
		 'hostname' => $data_array['hostname'],
		 'ip_address' => $data_array['ipaddress'],
		 'machine_type' => $data_array['machine_type'],
		 'machine_user' => $data_array['machine_user'],
		 'machine_task' => $data_array['machine_task'],
		 'service_date_eop' => $data_array['service_date_eop'],
		 'service_date_str' => $data_array['service_date_str'],
  ))
  ->execute();
  } catch (Exception $e) {
    drupal_set_message(t("Sorry, that didn't work. The name must be unique."), 'error');
    $inv_id = 0;
  }
  
  return $inv_id;
}




/**
 * function to get a list of computers for a given user
 * @method invdb_get_computer_list($user_name)
 * @param  string  $user_name
 * @param  array   $computer_list
 * 
 */
function invdb_get_computer_list($user_name){
  $stop = 0;
  
  $query = ("SELECT inv_id, hostname, user_id FROM zz_team_inv
             WHERE user_id = '" . $user_name . "'
            ");
  
  $result = db_query($query);
  
  foreach ($result as $row) {
    $computer_list[] = $row;
  }
  return $computer_list;
}// end of invdb_get_computer_list


//-------------------------------------------------------------------------
/**
 * function to get the hostname based on the inv_id
 * @method invdb_get_hostname($inv_id)
 * @param  string  $inv_id
 * @return  string  $hostname
 * 
 */
function invdb_get_hostname($inv_id){
  $stop = 0;
  
  $query = ("SELECT hostname  FROM zz_team_inv
             WHERE inv_id = '" . $inv_id . "'
            ");
  
  $result = db_query($query);
  
  foreach ($result as $row) {
    $rd[] = $row;
  }
  $hostname = $rd[0];

  return $hostname;
}// end of invdb_get_hostname
//-------------------------------------------------------------------------
