<?php


/**
 * @file  input.module
 * 
 *
 * input for system inventory data
 */



/**
 * Implements hook_menu().
 */
function input_menu() {
  $items = array();
  $items['input/inv'] = array(
    'title' => "Inventory Data Input",
    'description' => 'data input',
    //'page callback' => 'drupal_get_form',
    'page callback' => 'input_example_intro',
    'page arguments' => array('input_inventory_form'),
    'access callback' => TRUE,
    'expanded' => TRUE,
     ); // $items['input/inventory']



  $items['input/inv/bs'] = array(
    'title' => 'Base System Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('input_base_data_1'),
    'access callback' => TRUE,
    'description' => 'base data input',
    'file' => 'input_base_data.inc',
    'type' => MENU_NORMAL_ITEM,
  );
 
  $items['input/inv/os'] = array(
    'title' => 'Operating System Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('input_os_data_1'),
    //'page arguments' => array('wonk_example_wizard'),
    'access callback' => TRUE,
    'description' => 'base data input',
    'file' => 'input_os_data.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  
  $items['input/inv/sys'] = array(
    'title' => 'System Info File Data',
    'page callback' => 'drupal_get_form',
    //'page arguments' => array('input_os_data_1'),
    'page arguments' => array('skc_confuration_file_form'),
    'access callback' => TRUE,
    'description' => 'base data input',
    'file' => 'input_sys_data.inc',
    'type' => MENU_NORMAL_ITEM,
  );
 

  // Demo of dynamic query.
  $items['system/inventory'] = array(
  		'title' => 'System Inventory Page',
  		'description' => 'A full, paginated list of systems in the inventory.',
  		'page callback' => 'system_inventory_page',
  		'access arguments' => array('administer trails'),
  		'file' => 'input_inventory_display.inc',
  		'access callback' => TRUE,
  );

  return $items;
} // function input_menu()





/**
 * Page callback for our general info page.
 */
function input_example_intro() {
  $markup = '
  This site will provide an interface to collect information about the systems used by the <br/>
  AOSOS, JOB ZONE <span style="font-size:20px;letter-spacing: -1px;">  --- </span>  CAREER ZONE TEAM
    ';
  return array('#markup' => $markup);
}

